//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AshaERPEntities : DbContext
    {
        public AshaERPEntities()
            : base("name=AshaERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WMInv_Part> WMInv_Part { get; set; }
        public virtual DbSet<WMInv_PartInventoryProperty> WMInv_PartInventoryProperty { get; set; }
        public virtual DbSet<WMInv_PartSerial> WMInv_PartSerial { get; set; }
    }
}
