//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMInv_PartInventoryProperty
    {
        public string PartCode { get; set; }
        public string Title { get; set; }
        public string InventoryCode { get; set; }
        public string InventorySequenceCode { get; set; }
        public string InventoryABCCategoryCode { get; set; }
        public Nullable<bool> MainInventory { get; set; }
        public bool LotControl { get; set; }
        public bool ActiveQuantityBaseStock { get; set; }
        public string CreatorCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    
        public virtual WMInv_Part WMInv_Part { get; set; }
    }
}
