//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMInv_PartSerial
    {
        public string Code { get; set; }
        public string PartCode { get; set; }
        public string ParentPartSerialCode { get; set; }
        public string ParentPartCode { get; set; }
        public string WorkOrderCode { get; set; }
        public string PurchaseShipmentCode { get; set; }
        public string SalesShipmentCode { get; set; }
        public string StatusCode { get; set; }
        public string CreatorCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    
        public virtual WMInv_Part WMInv_Part { get; set; }
    }
}
